collections:
  top5:
    id: top5
    name: Top 5 Economics Journals
    name_cn: 经济学 TOP5
    journals:
      - AER
      - JPE
      - QJE
      - RES
      - ECTA
  fields:
    id: fields
    name: Econ Field Journals
    name_cn: 领域顶刊
    journals:
      - EJ
      - JEEA
      - EER
      - IER
      - JEP
      - AERI
      - GEB
      - JET
      - TE
      - RAND
      - AEJMICRO
      - JEBO
      - JDE
      - JPubE
      - JEH
      - JIE
      - JF
      - JFE
      - RFS
      - WD
      - RESTAT
      - AEJAPP
      - AEJPOL
      - QE
      - JUE
      - JME
      - AEJMACRO
      - JLE
      - JOE
      - JEEM
      - AJAE
      - FOODPOLICY
      - JAERE
      - LANDECON
      - LUP
      - ERE
      - JHE
      - JCE
      - CER
      - ENERGY
      - ECOLECON
      - LABECO
      - RED
      - JEDC
