collections:
  top5:
    id: top5
    name: Top 5 Economics Journals
    name_cn: 经济学 TOP5
    journals:
      - AER
      - JPE
      - QJE
      - RES
      - ECTA
  fields:
    id: fields
    name: Field Journals
    name_cn: 领域期刊
    journals: []
