schema_version: "1.0"
years:
  - 2025
  - 2026
journals:
  EER:
    platform: crossref
    issn: 0014-2921
    issue_url_template: https://www.sciencedirect.com/journal/european-economic-review/vol/{volume}/suppl/{issue}
  FOODPOLICY:
    platform: crossref
    issn: 0306-9192
    issue_url_template: https://www.sciencedirect.com/journal/food-policy/vol/{volume}/suppl/{issue}
  GEB:
    platform: crossref
    issn: 0899-8256
    issue_url_template: https://www.sciencedirect.com/journal/games-and-economic-behavior/vol/{volume}/suppl/{issue}
  JDE:
    platform: crossref
    issn: 0304-3878
    issue_url_template: https://www.sciencedirect.com/journal/journal-of-development-economics/vol/{volume}/suppl/{issue}
  JEBO:
    platform: crossref
    issn: 0167-2681
    issue_url_template: https://www.sciencedirect.com/journal/journal-of-economic-behavior-and-organization/vol/{volume}/suppl/{issue}
  JEEM:
    platform: crossref
    issn: 0095-0696
    issue_url_template: https://www.sciencedirect.com/journal/journal-of-environmental-economics-and-management/vol/{volume}/suppl/{issue}
  JET:
    platform: crossref
    issn: 0022-0531
    issue_url_template: https://www.sciencedirect.com/journal/journal-of-economic-theory/vol/{volume}/suppl/{issue}
  JFE:
    platform: crossref
    issn: 0304-405X
    issue_url_template: https://www.sciencedirect.com/journal/journal-of-financial-economics/vol/{volume}/suppl/{issue}
  JIE:
    platform: crossref
    issn: 0022-1996
    issue_url_template: https://www.sciencedirect.com/journal/journal-of-international-economics/vol/{volume}/suppl/{issue}
  JME:
    platform: crossref
    issn: 0304-3932
    issue_url_template: https://www.sciencedirect.com/journal/journal-of-monetary-economics/vol/{volume}/suppl/{issue}
  JOE:
    platform: crossref
    issn: 0304-4076
    issue_url_template: https://www.sciencedirect.com/journal/journal-of-econometrics/vol/{volume}/suppl/{issue}
  JPubE:
    platform: crossref
    issn: 0047-2727
    issue_url_template: https://www.sciencedirect.com/journal/journal-of-public-economics/vol/{volume}/suppl/{issue}
  JUE:
    platform: crossref
    issn: 0094-1190
    issue_url_template: https://www.sciencedirect.com/journal/journal-of-urban-economics/vol/{volume}/suppl/{issue}
  LUP:
    platform: crossref
    issn: 0264-8377
    issue_url_template: https://www.sciencedirect.com/journal/land-use-policy/vol/{volume}/suppl/{issue}
  WD:
    platform: crossref
    issn: 0305-750X
    issue_url_template: https://www.sciencedirect.com/journal/world-development/vol/{volume}/suppl/{issue}
  IER:
    platform: crossref
    issn: 0020-6598
    issue_url_template: https://onlinelibrary.wiley.com/toc/14682354/{volume}
  EJ:
    platform: crossref
    issn: 0013-0133
    issue_url_template: https://academic.oup.com/ej/issue/{volume}/{issue}
